FROM cloverdx-server:latest

# use e.g. 'docker run -e SANDBOX=MySandbox -e JOB_PATH=graph/mygraph.grf' to override
ENV SANDBOX=Example
ENV JOB_PATH=graph/graph.grf

COPY conf $CLOVER_HOME_DIR/conf
COPY sandboxes $CLOVER_HOME_DIR/sandboxes